name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Copy files via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 157.173.214.96
        username: u417347216
        password: ${{ secrets.SSH_PASSWORD }}
        port: 65002
        source: "./*"
        # Adjust the target path if your Hostinger setup uses a different folder
        target: "/home/u417347216/domains/sciencecoherence.com/public_html"
